Shelved/Models/CD.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Shelved.Models
{
    public class CD
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ApplicationUserId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }
        public string Artist { get; set; }
        public string Year { get; set; }

        [Display(Name = "Heard")]
        public bool IsHeard { get; set; }

        [Display(Name = "Album Cover")]
        public string ImagePath { get; set; }

        [Display(Name = "Genres")]
        public List<CDGenre> CDGenres { get; set; }

        [Display(Name = "Add To My Music")]
        public bool MyMusic { get; set; }

        [Display(Name = "Add To List List")]
        public bool ListenList { get; set; }

        [Display(Name = "Add To Wish List")]
        public bool WishList { get; set; }

        [Display(Name = "Add To Heard It List")]
        public bool HeardList { get; set; }

        [NotMapped]
        public IFormFile File { get; set; }
    }
}

Shelved/Models/ViewModels/CDViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Shelved.Models.ViewModels
{
    public class CDViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ApplicationUserId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }
        public string Artist { get; set; }
        public string Year { get; set; }

        [Display(Name = "I've Heard This")]
        public bool IsHeard { get; set; }

        [Display(Name = "Album Cover")]
        public string ImagePath { get; set; }

        [Required(ErrorMessage = "Please Select Genre(s)")]
        [Display(Name = "Genres")]
        public List<int> GenreIds { get; set; }
        public GenresForCDs GenresForCDs { get; set; }

        [Display(Name = "Add To My Music")]
        public bool MyMusic { get; set; }

        [Display(Name = "Add To Listen List")]
        public bool ListenList { get; set; }

        [Display(Name = "Add To Wish List")]
        public bool WishList { get; set; }

        [Display(Name = "Add To Heard That List")]
        public bool HeardList { get; set; }
        public IFormFile File { get; set; }

    }
}

Shelved/Controllers/CDsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using ReflectionIT.Mvc.Paging;
using Shelved.Data;
using Shelved.Models;
using Shelved.Models.ViewModels;

namespace Shelved.Controllers
{
    [Authorize]
    public class CDsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public CDsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: CDs
        public async Task<IActionResult> Index(string searchMusic, int page = 1, string sortBy = "Title")
        {
            var user = await GetCurrentUserAsync();


            if (string.IsNullOrWhiteSpace(searchMusic))
            {
                var cds = _context.CD
                         .AsNoTracking()
                .Include(c => c.CDGenres)
                   .ThenInclude(cg => cg.GenresForCDs)
                .Where(c => c.MyMusic == true && c.ApplicationUserId == user.Id);


                var model = await PagingList.CreateAsync(
                             cds, 10, page, sortBy, "Title");

                model.RouteValue = new RouteValueDictionary {
                    { "searchBooks", searchMusic}
                     };

                return View(model);
            }
            else
            {
                var cds = _context.CD
                      .AsNoTracking()
                .Where(c => c.MyMusic == true && c.ApplicationUserId == user.Id &&
                (c.Title.Contains(searchMusic) || c.Artist.Contains(searchMusic)))
                    .Include(c => c.CDGenres)
                        .ThenInclude(cg => cg.GenresForCDs);

                var model = await PagingList.CreateAsync(
                                           cds, 10, page, sortBy, "Title");

                model.RouteValue = new RouteValueDictionary {
                    { "searchBooks", searchMusic}
                     };

                return View(model);
            }
        }

        // GET: Listen List Music
        public async Task<IActionResult> ListenList(string searchListenList)
        {
            var user = await GetCurrentUserAsync();

            if (searchListenList == null)
            {
                var cds = _context.CD
            .Include(c => c.CDGenres)
            .ThenInclude(cg => cg.GenresForCDs)
            .Where(c => c.ApplicationUserId == user.Id & c.ListenList == true);
                return View(await cds.ToListAsync());
            }
            else
            {
                var cds = _context.CD
                .Where(c => c.ListenList == true && c.ApplicationUserId == user.Id &&
                (c.Title.Contains(searchListenList) || c.Artist.Contains(searchListenList)))
                .Include(c => c.CDGenres)
                .ThenInclude(cg => cg.GenresForCDs);
                return View(await cds.ToListAsync());
            }

        }


        // GET: Wish List Music
        public async Task<IActionResult> WishList(string searchWishList)
        {
            var user = await GetCurrentUserAsync();

            if (searchWishList == null)
            {
                var cds = _context.CD
            .Include(c => c.CDGenres)
            .ThenInclude(cg => cg.GenresForCDs)
            .Where(c => c.ApplicationUserId == user.Id && c.WishList == true);
                return View(await cds.ToListAsync());
            }
            else
            {
                var cds = _context.CD
                .Where(c => c.WishList == true && c.ApplicationUserId == user.Id &&
                (c.Title.Contains(searchWishList) || c.Artist.Contains(searchWishList)))
                    .Include(c => c.CDGenres)
                         .ThenInclude(cg => cg.GenresForCDs);
                return View(await cds.ToListAsync());
            }
        }


        // GET: Heard List Movies
        public async Task<IActionResult> HeardList(string searchHeardList)
        {
            var user = await GetCurrentUserAsync();

            if (searchHeardList == null)
            {
                var cds = _context.CD
                .Include(c => c.CDGenres)
                .ThenInclude(cg => cg.GenresForCDs)
                .Where(c => c.ApplicationUserId == user.Id && c.HeardList == true);
                return View(await cds.ToListAsync());
            }
            else
            {
                var cds = _context.CD
                .Where(c => c.HeardList == true && c.ApplicationUserId == user.Id &&
                (c.Title.Contains(searchHeardList) || c.Artist.Contains(searchHeardList)))
                    .Include(c => c.CDGenres)
                        .ThenInclude(cg => cg.GenresForCDs);
                return View(await cds.ToListAsync());
            }
        }


        // GET: CDs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var user = await GetCurrentUserAsync();

            if (id == null)
            {
                return NotFound();
            }

            var cD = await _context.CD
                .Where(c => c.ApplicationUserId == user.Id)
                .Include(c => c.CDGenres)
                .ThenInclude(cg => cg.GenresForCDs)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cD == null)
            {
                return NotFound();
            }

            return View(cD);
        }

        // GET: CDs/Create
        public async Task<IActionResult> Create()
        {
            var user = await GetCurrentUserAsync();

            ViewData["ApplicationUserId"] = new SelectList(_context.ApplicationUser, "Id", "Id");
            ViewData["GenresForCDs"] = new SelectList(_context.GetGenresForCD, "Id", "Description");

            return View();
        }

        // POST: CDs/Create      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ApplicationUserId,Artist,Year,IsHeard,ImagePath,GenreIds,MyMusic,ListenList,HeardList,WishList,File")] CDViewModel cdViewModel, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();

                // Add CD to database
                var cdModel = new CD
                {
                    Title = cdViewModel.Title,
                    Artist = cdViewModel.Artist,
                    Year = cdViewModel.Year,
                    IsHeard = cdViewModel.IsHeard,
                    ImagePath = cdViewModel.ImagePath,
                    ApplicationUserId = user.Id,
                    MyMusic = cdViewModel.MyMusic,
                    ListenList = cdViewModel.ListenList,
                    WishList = cdViewModel.WishList,
                    HeardList = cdViewModel.HeardList
                };

                if (cdViewModel.File != null && cdViewModel.File.Length > 0)
                {
                    var fileName = Guid.NewGuid().ToString() + Path.GetFileName(cdViewModel.File.FileName); //getting path of actual file name
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", fileName); //creating path combining file name w/ www.root\\images directory
                    using (var fileSteam = new FileStream(filePath, FileMode.Create)) //using filestream to get the actual path
                    {
                        await cdViewModel.File.CopyToAsync(fileSteam);
                    }
                    cdModel.ImagePath = fileName;

                }

                _context.Add(cdModel);
                await _context.SaveChangesAsync();

                // Add genres to CD
                cdModel.CDGenres = cdViewModel.GenreIds.Select(genreId => new CDGenre
                {
                    CDId = cdModel.Id,
                    GenreId = genreId
                }).ToList();

                // Save again to database
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            ViewData["ApplicationUserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", cdViewModel.ApplicationUserId);
            ViewData["GenresForCDs"] = new SelectList(_context.GetGenresForCD, "Id", "Description", cdViewModel.GenreIds);
            return View(cdViewModel);
        }

        // GET: CDs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var user = await GetCurrentUserAsync();

            if (id == null)
            {
                return NotFound();
            }

            var cD = await _context.CD
                .Include(c => c.CDGenres)
                 .ThenInclude(cg => cg.GenresForCDs)
                .FirstOrDefaultAsync(c => c.Id == id);

            if (cD == null)
            {
                return NotFound();
            }
            var cDViewModel = new CDViewModel
            {
                Id = cD.Id,
                Title = cD.Title,
                Artist = cD.Artist,
                Year = cD.Year,
                IsHeard = cD.IsHeard,
                File = cD.File,
                ImagePath = cD.ImagePath,
                ApplicationUserId = user.Id,
                MyMusic = cD.MyMusic,
                ListenList = cD.ListenList,
                WishList = cD.WishList,
                HeardList = cD.HeardList,
                GenreIds = cD.CDGenres.Select(bg => bg.GenreId).ToList()
            };

Shelved/Views/CDs/Delete.cshtml
@model Shelved.Models.CD

@{
    ViewData["Title"] = "Delete";
}


<h3>Are you sure you want to delete this Album?</h3>
<div>
    <div>
        <img style="max-height: 250px; min-height: 100px; max-width:200px; min-width:100px;" class="img-responsive bookImage" src="@Url.Content("~/images/" + Model.ImagePath)" alt="" />
    </div>
    <h3>
        @Html.DisplayFor(model => model.Title)
    </h3>

    <h4>
        @Html.DisplayFor(model => model.Artist)
    </h4>
    <br />

    <h6>This Album is on the following Lists:</h6>
    <dl>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MyMusic)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MyMusic)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.WishList)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.WishList)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ListenList)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ListenList)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.HeardList)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.HeardList)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> &nbsp;
        <a class="btn btn-outline-dark" asp-action="Index">Back to My Music</a>
    </form>
</div>
<br />
<br />
<br />

Shelved/Views/CDs/HeardList.cshtml
@model IEnumerable<Shelved.Models.CD>

@{
    ViewData["Title"] = "HeardList";
}

<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CDs" asp-action="Index">My Music</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CDs" asp-action="WishList">Wish List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CDs" asp-action="ListenList">Listen List</a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" asp-area="" asp-controller="CDs" asp-action="HeardList">I've Heard That</a>
                    </li>&nbsp;
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CDs" asp-action="Index">My Music</a>
                    </li> &nbsp;
                    <li class="nav-item">
                        <form method="get" class="form-inline" asp-action="HeardList" asp-controller="CDs">
                            <label></label>
                            <input name="searchHeardList" class="form-control" placeholder="Search by Title or Artist" /> &nbsp;
                            <button type="submit" class="btn btn-outline-dark">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
                            </button>
                        </form>
                    </li> &nbsp; &nbsp;
                    <li class="nav-item">
                        <p>
                            <a class="btn btn-outline-danger" asp-action="Create">Add An Album</a>
                        </p>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</body>

<div>
    <div style="text-align: center">
        <img align="center" src="~/images//music3.jpg" alt="music" style="max-height: 300px; min-height: 200px; max-width:1200px; min-width:1000px;">  &nbsp;
    </div>

</div>


<div class="container">
    <div class="row justify-content-between">

        @foreach (var item in Model)
        {
            <div class="col-3">
                <div class="card indexCard">
                    <div class="card-body">
                        <h5 class="card-title">

                            @Html.DisplayFor(modelItem => item.Title)

                        </h5>
                        <p class="card-text">
                            By:
                            @Html.DisplayFor(modelItem => item.Artist)
                        </p>
                        <div>
                            <img style="max-height: 140px; min-height: 120px;" class="img-responsive" src="@Url.Content("~/images/" + item.ImagePath)" alt="" /> &nbsp;
                            <a class="btn btn-outline-dark mt-3 btn-create-new-group" asp-action="Details" asp-route-id="@item.Id">Details</a>

                        </div>
                        &nbsp; &nbsp;

                        <p class="card-text">
                            Published:
                            @Html.DisplayFor(modelItem => item.Year)
                        </p>
                        <p class="card-text">
                            @Html.DisplayNameFor(model => model.IsHeard)
                            @Html.DisplayFor(modelItem => item.IsHeard)
                        </p>
                        <p class="card-text">
                            Genres:

                            @foreach (var genre in item.CDGenres)
                            {
                                @Html.DisplayFor(modelItem => genre.GenresForCDs.Description) <br />
                            } &nbsp;
                        </p>


                    </div>
                </div>
            </div>
        }
    </div>
</div>
<br />
<br />

Shelved/Views/CDs/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<Shelved.Models.CD>
@using ReflectionIT.Mvc.Paging
@addTagHelper *, ReflectionIT.Mvc.Paging


@{
    ViewData["Title"] = "Index";
}

<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">

            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="navbar-brand" asp-area="" asp-controller="CDs" asp-action="Index">My Music</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CDs" asp-action="WishList">Wish List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CDs" asp-action="ListenList">Listen List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CDs" asp-action="HeardList">I've Heard That</a>
                    </li>&nbsp;
                    <li class="nav-item">
                        <form method="get" class="form-inline">
                            <label></label>
                            <input name="searchMusic" class="form-control" placeholder="Search by Album or Artist"
                                   value="@Model.RouteValue["searchMusic"]" /> &nbsp; &nbsp;
                            <button type="submit" class="btn btn-outline-dark">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
                            </button>
                        </form>
                    </li>  &nbsp; &nbsp;
                    <li class="nav-item">
                        <p>
                            <a class="btn btn-outline-danger" asp-action="Create">Add An Album</a>
                        </p>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</body>



<div>
    <div style="text-align: center">
        <img align="center" src="~/images//music3.jpg" alt="books" style="max-height: 300px; min-height: 200px; max-width:1200px; min-width:1000px;">  &nbsp;
    </div>

</div>

<nav aria-label="CDs">
    @await this.Component.InvokeAsync("Pager", new { pagingList = this.Model })
</nav>

<div class="container">
    <div class="row justify-content-between">

        @foreach (var item in Model)
        {
            <div class="col-3">
                <div class="card indexCard">
                    <div class="card-body">
                        <h5 class="card-title">

                            @Html.DisplayFor(modelItem => item.Title)

                        </h5>
                        <p class="card-text">
                            By:
                            @Html.DisplayFor(modelItem => item.Artist)
                        </p>
                        <div>
                            <img style="max-height: 100px; min-height: 80px;" class="img-responsive" src="@Url.Content("~/images/" + item.ImagePath)" alt="" /> &nbsp;
                            <a class="btn btn-outline-dark mt-3 btn-create-new-group" asp-action="Details" asp-route-id="@item.Id">Details</a>

                        </div>
                        &nbsp; &nbsp;

                        <p class="card-text">
                            Published:
                            @Html.DisplayFor(modelItem => item.Year)
                        </p>
                        <p class="card-text">
                            @Html.DisplayNameFor(model => model.IsHeard)
                            @Html.DisplayFor(modelItem => item.IsHeard)
                        </p>
                        <p class="card-text">
                            Genres:

                            @foreach (var genre in item.CDGenres)
                            {
                                @Html.DisplayFor(modelItem => genre.GenresForCDs.Description) <br />
                            } &nbsp;
                        </p>


                    </div>
                </div>
            </div>
        }
    </div>
</div>

<nav aria-label="CDs">
    <vc:pager paging-list="@Model" />
</nav>
<br />
<br />

Shelved/Views/CDs/ListenList.cshtml
@model IEnumerable<Shelved.Models.CD>

@{
    ViewData["Title"] = "ListenList";
}

<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CDs" asp-action="Index">My Music</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CDs" asp-action="WishList">Wish List</a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" asp-area="" asp-controller="CDs" asp-action="ListenList">Listen List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CDs" asp-action="HeardList">I've Heard That</a>
                    </li>&nbsp;
                    <li class="nav-item">
                        <form method="get" class="form-inline" asp-action="ListenList" asp-controller="CDs">
                            <label></label>
                            <input name="searchListenList" class="form-control" placeholder="Search by Title or Artist" /> &nbsp;
                            <button type="submit" class="btn btn-outline-dark">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
                            </button>
                        </form>
                    </li> &nbsp; &nbsp;
                    <li class="nav-item">
                        <p>
                            <a class="btn btn-outline-danger" asp-action="Create">Add An Album</a>
                        </p>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</body>

<div>
    <div style="text-align: center">
        <img align="center" src="~/images//music3.jpg" alt="music" style="max-height: 300px; min-height: 200px; max-width:1200px; min-width:1000px;">  &nbsp;
    </div>

</div>


<div class="container">
    <div class="row justify-content-between">

        @foreach (var item in Model)
        {
            <div class="col-3">
                <div class="card indexCard">
                    <div class="card-body">
                        <h5 class="card-title">

                            @Html.DisplayFor(modelItem => item.Title)

                        </h5>
                        <p class="card-text">
                            By:
                            @Html.DisplayFor(modelItem => item.Artist)
                        </p>
                        <div>
                            <img style="max-height: 140px; min-height: 120px;" class="img-responsive" src="@Url.Content("~/images/" + item.ImagePath)" alt="" /> &nbsp;
                            <a class="btn btn-outline-dark mt-3 btn-create-new-group" asp-action="Details" asp-route-id="@item.Id">Details</a>

                        </div>
                        &nbsp; &nbsp;

                        <p class="card-text">
                            Published:
                            @Html.DisplayFor(modelItem => item.Year)
                        </p>
                        <p class="card-text">
                            @Html.DisplayNameFor(model => model.IsHeard)
                            @Html.DisplayFor(modelItem => item.IsHeard)
                        </p>
                        <p class="card-text">
                            Genres:

                            @foreach (var genre in item.CDGenres)
                            {
                                @Html.DisplayFor(modelItem => genre.GenresForCDs.Description) <br />
                            } &nbsp;
                        </p>


                    </div>
                </div>
            </div>
        }
    </div>
</div>
<br />
<br />

Shelved/Views/CDs/WishList.cshtml
@model IEnumerable<Shelved.Models.CD>

@{
    ViewData["Title"] = "WishList";
}

<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CDs" asp-action="Index">My Music</a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" asp-area="" asp-controller="CDs" asp-action="WishList">Wish List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CDs" asp-action="ListenList">Listen List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="CDs" asp-action="HeardList">I've Heard That</a>
                    </li>&nbsp;
                    <li class="nav-item">
                        <form method="get" class="form-inline" asp-action="WishList" asp-controller="CDs">
                            <label></label>
                            <input name="searchWishList" class="form-control" placeholder="Search by Title or Artist" /> &nbsp;
                            <button type="submit" class="btn btn-outline-dark">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
                            </button>
                        </form>
                    </li> &nbsp; &nbsp;
                    <li class="nav-item">
                        <p>
                            <a class="btn btn-outline-danger" asp-action="Create">Add An Album</a>
                        </p>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</body>

<div>
    <div style="text-align: center">
        <img align="center" src="~/images//music3.jpg" alt="music" style="max-height: 300px; min-height: 200px; max-width:1200px; min-width:1000px;">  &nbsp;
    </div>

</div>



<div class="container">
    <div class="row justify-content-between">

        @foreach (var item in Model)
        {
            <div class="col-3">
                <div class="card indexCard">
                    <div class="card-body">
                        <h5 class="card-title">

                            @Html.DisplayFor(modelItem => item.Title)

                        </h5>
                        <p class="card-text">
                            By:
                            @Html.DisplayFor(modelItem => item.Artist)
                        </p>
                        <div>
                            <img style="max-height: 140px; min-height: 120px;" class="img-responsive" src="@Url.Content("~/images/" + item.ImagePath)" alt="" /> &nbsp;
                            <a class="btn btn-outline-dark mt-3 btn-create-new-group" asp-action="Details" asp-route-id="@item.Id">Details</a>

                        </div>
                        &nbsp; &nbsp;

                        <p class="card-text">
                            Published:
                            @Html.DisplayFor(modelItem => item.Year)
                        </p>
                        <p class="card-text">
                            @Html.DisplayNameFor(model => model.IsHeard)
                            @Html.DisplayFor(modelItem => item.IsHeard)
                        </p>
                        <p class="card-text">
                            Genres:

                            @foreach (var genre in item.CDGenres)
                            {
                                @Html.DisplayFor(modelItem => genre.GenresForCDs.Description) <br />
                            } &nbsp;
                        </p>


                    </div>
                </div>
            </div>
        }
    </div>
</div>
<br />
<br />